# --- Transparência ---
background_opacity 0.8
# background_blur 1  # (Descomente se o seu sistema suportar blur, como no Hyprland)

# --- Estética Moderna ---
window_padding_width 15
font_family      JetBrainsMono Nerd Font
font_size        12.0

# --- Cores (Estilo Catppuccin Mocha) ---
background #11111b
foreground #cdd6f4
selection_background #585b70
selection_foreground #cdd6f4
url_color #f5e0dc
cursor #f5e0dc

# --- Bordas e Abas ---
active_border_color #b4befe
inactive_border_color #6c7086
tab_bar_style powerline
