bind = SUPER, F, exec, wofi --show drun
bind = SUPER, B, exec, killall waybar || waybar
bind = SUPER_SHIFT, S, exec, grim -g "$(slurp)" - | wl-copy && hyprctl dispatch focusmonitor +1 && hyprctl dispatch focusmonitor -1
